openapi: 3.0.0
info:
  title: casino-ws
  version: 1.0.0
paths:
  /ws:
    x-yc-apigateway-websocket-connect:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ВСТАВЬТЕ_ID_ФУНКЦИИ
        tag: "$latest"
        service_account_id: ВСТАВЬТЕ_ID_СЕРВИСНОГО_АККАУНТА
    x-yc-apigateway-websocket-message:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ВСТАВЬТЕ_ID_ФУНКЦИИ
        tag: "$latest"
        service_account_id: ВСТАВЬТЕ_ID_СЕРВИСНОГО_АККАУНТА
    x-yc-apigateway-websocket-disconnect:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ВСТАВЬТЕ_ID_ФУНКЦИИ
        tag: "$latest"
        service_account_id: ВСТАВЬТЕ_ID_СЕРВИСНОГО_АККАУНТА
